import calc
num1=int(input("Enter num1:"))
num2=int(input("Enter num2:"))
sum=calc.add(num1,num2)
print("sum",sum)
difference=calc.subtract(num1,num2)
print("difference",difference)
product=calc.multiply(num1,num2)
print("product",product)
divide=calc.divide(num1,num2)
print("divide",divide)
